### ISSUE TITLE
match making

### ISSUE THREAD

**Issue by geeksesi** [AmirRezaM75/skull-king#3]
as a solo player, it isn't easy to find friends and play.

- [ ] on making a lobby choose whether is it public or private
- [ ] create lobby action 
- [ ] on `play` if there is a public lobby join, else make a lobby
- [ ] On lobby creation choose the limitation of users

**Comment by AmirRezaM75** [comment]
You are correct, and I will implement the 'joining public lobby' feature once we have a minimum of 500 users. It is not beneficial with a small user base because finding active lobbies would be so hard.

**Comment by AmirRezaM75** [comment]
Hi @geeksesi.
I new release you are able to create public lobbies.
Later on I'll work on private lobbies and user capacity.
