### ISSUE TITLE
Bug: forget password

### ISSUE THREAD

**Issue by parsariyahi** [AmirRezaM75/skull-king#4]
in web site when we want to reset our password, it won't change it when we complete the process

**Comment by parsariyahi** [comment]
yep you're right the reset password is working, I was using my ``email`` instead of ``username``, I think it would be better if you use the email as well as username, because the concept of a unique thing between users is working for both email and username.

**Comment by AmirRezaM75** [comment]
Good to hear that you could login to the platform.
You are right. I'll add the ability to login with both username or password.

**Comment by AmirRezaM75** [comment]
@parsariyahi done
