### ISSUE TITLE
Show first player indicator when bidding

### ISSUE THREAD

**Issue by Maxouwell** [AmirRezaM75/skull-king#8]
Hello and thanks for the game.

Could it be possible to add the spinning animation on the next first player while in the bidding phase ?
It's tricky for new players to remember who played first on previous round.

Thanks

**Comment by AmirRezaM75** [comment]
Hi,
that's reasonable. I'll work on that at the weekend.

**Comment by AmirRezaM75** [comment]
Hi @Maxouwell ,
This is implemented in new release. In bidding time, I use gradient blue background for the one is going to start the round,
